/**
* The following code is automatically generated by the program . 
* Do not modify it manually !
*/
package org.seckill.entity;

import org.springframework.stereotype.Repository;

import java.util.Date;

//TODO 替代JDK8的LocalDate替代Date
@Repository
public class SuccessKilled {
	/**
	 * 秒杀商品id
	 */
	private long seckillId;
	/**
	 * 用户手机号
	 */
	private long userPhone;
	/**
	 * 状态标示：-1：无效 0：成功 1：已付款
	 */
	private int state;
	/**
	 * 创建时间
	 */
	private Date createTime;

	private Seckill seckill;

	public long getSeckillId() {	return this.seckillId;	}
	public void setSeckillId(long seckillId) {	this.seckillId = seckillId;	}
	public long getUserPhone() {	return this.userPhone;	}
	public void setUserPhone(long userPhone) {	this.userPhone = userPhone;	}
	public int getState() {	return this.state;	}
	public void setState(int state) {	this.state = state;	}
	public Date getCreateTime() {	return this.createTime;	}
	public void setCreateTime(Date createTime) {	this.createTime = createTime;	}

	public Seckill getSeckill() {
		return seckill;
	}

	public void setSeckill(Seckill seckill) {
		this.seckill = seckill;
	}

	@Override
	public String toString() {
		return "SuccessKilled{" +
				"seckillId=" + seckillId +
				", userPhone=" + userPhone +
				", state=" + state +
				", createTime=" + createTime +
				", seckill=" + seckill +
				'}';
	}
}
